### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by abulte** [opendatateam/udata-piwik#20]
We need some tests on this extension.

The difficulty is that we need a Piwik instance to do some end to end testing.

It is proposed to:
- [x] rely on a test docker piwik instance, either for local or CI testing #21 
- [x] publish the docker image to the docker hub #22
- [ ] switch this repo to circle CI v2 and use the above docker image #23
- [x] write some tests ;-) #24
